tap "espanso/espanso"
tap "go-task/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "jeffreywildman/virt-manager"
tap "jesseduffield/lazygit"
tap "warrensbox/tap"
brew "gettext"
brew "librsvg"
brew "python@3.10"
brew "ansible"
brew "antigen"
brew "autoconf"
brew "autojump"
brew "commitizen"
brew "consul"
brew "direnv"
brew "docker-compose"
brew "fzf"
brew "go"
brew "gstreamer"
brew "gst-plugins-base"
brew "gst-libav"
brew "libnice"
brew "gst-plugins-bad"
brew "gst-plugins-good"
brew "gst-plugins-ugly"
brew "hugo"
brew "jq"
brew "mas"
brew "nomad"
brew "packer"
brew "pandoc"
brew "pipenv"
brew "poetry"
brew "pre-commit"
brew "pyenv"
brew "pyenv-virtualenv"
brew "shellcheck"
brew "starship"
brew "syncthing"
brew "terraform-docs"
brew "tmux"
brew "vault"
brew "go-task/tap/go-task"
brew "jesseduffield/lazygit/lazygit"
brew "warrensbox/tap/tfswitch"
cask "1password"
cask "1password-cli"
cask "alacritty"
cask "balenaetcher"
cask "calibre"
cask "docker"
cask "espanso"
cask "firefox"
cask "font-fira-code"
cask "hammerspoon"
cask "hiddenbar"
cask "inkscape"
cask "karabiner-elements"
cask "keepassxc"
cask "multipass"
cask "obsidian"
cask "prusaslicer"
cask "slack"
cask "spotify"
cask "sqlectron"
cask "telegram"
cask "visual-studio-code"
cask "whatsapp"
mas "Brother P-touch Editor", id: 1453365242
mas "EOBD-Facile", id: 976630793
mas "Focalboard", id: 1556908618
mas "GarageBand", id: 682658836
mas "Home Assistant", id: 1099568401
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Serial", id: 877615577
mas "Tailscale", id: 1475387142
