[tasks.default]
links = [
    [
        ".hammerspoon",
    ],
    [
        ".tmux.conf",
        "./tmux/.tmux.conf",
    ],
    [
        ".config/alacritty/alacritty.yml",
    ],
    [
        ".config/karabiner/karabiner.json",
    ],
    [
        ".config/starship.toml",
    ],
    [
        ".config/obnctl/config.toml",
    ],
    [
        ".zshrc",
        "./zsh/.zshrc",
    ],
    [
        ".zprofile",
        "./zsh/.zprofile",
    ],
    [
        "/Users/msh/Library/Application Support/espanso/match/base.yml",
        "./espanso/base.yml",
    ],
    [
        "/Users/msh/Library/Application Support/espanso/config/default.yml",
        "./espanso/default.yml",
    ],
    [
        "/Users/msh/Library/Application Support/lazygit/config.yml",
        "./lg/config.yml",
    ],
    [
        ".config/nvim",
    ],
]
