---
version: '3'

tasks:
  bootstrap:
    desc: Prepare for launch
    summary: |
      Bootstrap your environment

      This will download homebrew, install golang, build the latest version of homemaker.

    cmds:
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - mkdir -p ~/bin
      - brew install go
      - go install github.com/FooSoft/homemaker@latest
      - cp ~/go/bin/homemaker ~/bin
    status:
      - test -f ~/bin/homemaker

  packages:
    deps: [bootstrap]
    desc: Install brew dump
    cmds:
      - brew bundle install --file=./Brewfile-$DEVICE

  dump-packages:
    deps: [bootstrap]
    desc: Dump a brewfile
    cmds:
      - brew bundle dump --force --file=./Brewfile-$DEVICE

  tmux_tpm:
    deps: [bootstrap]
    desc: install tmux tpm
    cmds:
      - git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    status:
      - test -d ~/.tmux/plugins/tpm

  homemaker:
    # deps: [bootstrap, extra_config]
    desc: Home is an invention on which no one has yet improved
    cmds:
      - ~/bin/homemaker -clobber config.toml .