[character]
symbol = "➜"
error_symbol = "✗"
use_symbol_for_status = true

[terraform]
show_version = true

[kubernetes]
symbol = "⛵ "
style = "dimmed green"
disabled = false


[git_branch]
symbol = "🌱 "

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "👅"
deleted = "🗑"
prefix = "::"
suffix = ":: "



[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"